# =============================================================================
# Static content for the "Methods & help" tab.
# =============================================================================

methods_ui <- function() {
  withMathJax(div(
    style = "max-width: 900px;",

    h3("What this app does"),
    p("It helps you choose a sample size for a two-arm trial (treatment vs",
      "control) with a continuous outcome, such as blood pressure or a",
      "symptom score. It compares two ways of answering \"how likely is this",
      "study to succeed?\":"),
    tags$ul(
      tags$li(strong("Frequentist power"), "assumes the true effect is known",
              "exactly (your expected effect) and asks how often a t-test",
              "would be significant."),
      tags$li(strong("Bayesian assurance"), "(also called the probability of",
              "success) admits that the true effect is uncertain. It averages",
              "the chance of success over every effect size you consider",
              "plausible, weighted by how plausible you think it is.")),
    p("Assurance is usually lower than power when you are optimistic about the",
      "effect, because it also counts the scenarios in which the treatment",
      "works less well than hoped, or not at all."),

    h3("Quick guide to the inputs"),
    tags$dl(
      tags$dt("Design prior"),
      tags$dd("Your honest belief about the true difference in means",
              "(treatment minus control) before the study. The mean is your",
              "best guess, and the SD says how unsure you are: about 95% of the",
              "effects you consider plausible lie within mean \u00B1 2 SD.",
              "The design prior is only used to plan the study."),
      tags$dt("Analysis prior"),
      tags$dd("The prior that will actually be used when the trial data are",
              "analysed. Regulators and reviewers often prefer a sceptical",
              "prior (centred at 0) or a vague one (very large SD, which lets",
              "the data speak). Using the design prior here is simpler, but",
              "it builds your optimism into the final analysis."),
      tags$dt("Outcome SD"),
      tags$dd("How much the outcome varies from person to person within a",
              "group, assumed known and the same in both groups."),
      tags$dt("Clinically meaningful difference (margin)"),
      tags$dd("For one-sided tests, you can require the trial to show that the",
              "effect exceeds a margin (for example, the minimal clinically",
              "important difference), not just that it is above zero."),
      tags$dt("Allocation ratio and dropout"),
      tags$dd("The ratio sets the treatment-group size relative to the",
              "control group (2 means twice as many on treatment). Dropout",
              "does not change the calculations, which refer to analysable",
              "participants; it only inflates the number you need to enrol."),
      tags$dt("Target"),
      tags$dd("The probability of success you are aiming for (commonly 80% or",
              "90%). The app finds the smallest sample size that reaches it.")),

    h3("The model"),
    p("Outcomes are \\(y_{Ti} \\sim N(\\mu_T, \\sigma^2)\\) in",
      "\\(n_T\\) treated participants and \\(y_{Ci} \\sim N(\\mu_C, \\sigma^2)\\)",
      "in \\(n_C\\) controls, with \\(\\sigma\\) known. The effect is",
      "\\(\\Delta = \\mu_T - \\mu_C\\)."),
    p("Design prior: \\(\\Delta \\sim N(m_d, s_d^2)\\). Analysis prior:",
      "\\(\\Delta \\sim N(m_a, s_a^2)\\), with a flat prior on the common level",
      "of the two arms."),
    p("With margin \\(m \\ge 0\\) and threshold \\(\\alpha\\), the trial is a",
      "success when the posterior (under the analysis prior) is convincing:"),
    tags$ul(
      tags$li("One-sided, treatment > control:",
              "\\(P(\\Delta > m \\mid \\text{data}) > 1-\\alpha\\)"),
      tags$li("One-sided, treatment < control:",
              "\\(P(\\Delta < -m \\mid \\text{data}) > 1-\\alpha\\)"),
      tags$li("Two-sided: \\(P(\\Delta > 0 \\mid \\text{data}) > 1-\\alpha/2\\)",
              "or \\(P(\\Delta < 0 \\mid \\text{data}) > 1-\\alpha/2\\).",
              "Note that this counts a convincing effect in either direction,",
              "including the unexpected one; the summary says how much of the",
              "assurance comes from that.")),
    p("Assurance is",
      "$$\\text{Assurance}(n) = \\int P(\\text{success} \\mid \\Delta, n)\\,",
      "\\pi_d(\\Delta)\\, d\\Delta,$$",
      "the probability of success averaged over the design prior",
      "\\(\\pi_d\\). The \"Success vs true effect\" tab shows",
      "\\(P(\\text{success} \\mid \\Delta, n)\\) together with \\(\\pi_d\\)."),

    h3("How it is computed"),
    tags$ul(
      tags$li(strong("Simulated assurance"), "(the default) comes from",
              code("bayesassurance::bayes_sim_unbalanced()"), "(Pan & Banerjee).",
              "For each sample size the package draws a true effect from the",
              "design prior, simulates a trial, computes the posterior under",
              "the analysis prior and checks the success rule, repeating this",
              "many times. The shaded band is the 95% Monte Carlo interval.",
              "In the package's parameterisation, prior variances are relative",
              "to \\(\\sigma^2\\), so a prior SD \\(s\\) enters as",
              "\\(s^2/\\sigma^2\\). The full mapping is documented in",
              code("R/calculations.R"), "."),
      tags$li(strong("Exact assurance."), "Because \\(\\sigma\\) is known,",
              "everything is normal and assurance has a closed form. The",
              "observed difference \\(\\bar d\\) has variance",
              "\\(v = \\sigma^2(1/n_T + 1/n_C)\\), and success reduces to",
              "\\(\\bar d\\) crossing a cut-off. Marginally over the design",
              "prior, \\(\\bar d \\sim N(m_d, s_d^2 + v)\\). The app uses this",
              "exact formula for the dotted check line, the sample-size",
              "finder, the sensitivity plots and the success-vs-effect curve.",
              "The included tests confirm that it agrees with the package's",
              "simulation."),
      tags$li(strong("Frequentist power"), "is the two-sample t-test power,",
              "using a noncentral t distribution with \\(n_T+n_C-2\\) degrees",
              "of freedom and the design prior mean as the true effect. It is",
              "identical to", code("stats::power.t.test()"), "for equal",
              "groups, and extends it to unequal groups and a margin."),
      tags$li(strong("Assurance ceiling."), "As the sample size grows, the",
              "data overwhelm the analysis prior and the trial succeeds",
              "exactly when the true effect lies beyond the success threshold.",
              "Assurance therefore cannot exceed the design-prior probability",
              "of that event (for one-sided tests: \\(P(\\Delta > m)\\) under",
              "the design prior). If your target is above this ceiling, no",
              "sample size can reach it.")),
    p("The package's closed-form function", code("assurance_nd_na()"),
      "is not used. It ties the analysis prior mean to the null value, and it",
      "does not match the exact posterior-probability assurance when the",
      "analysis prior is informative."),

    h3("Tips"),
    tags$ul(
      tags$li("Simulation cost grows with the square of the sample size. Use",
              "the exact engine for quick exploration, then confirm with the",
              "simulation."),
      tags$li("Use the bookmark button to get a link that restores all your",
              "inputs."),
      tags$li("Save scenarios on the Results tab to compare assumptions side",
              "by side.")),

    h3("References"),
    tags$ul(
      tags$li("O'Hagan A, Stevens JW (2001). Bayesian assessment of sample",
              "size for clinical trials of cost-effectiveness.",
              em("Medical Decision Making"), "21(3):219-230."),
      tags$li("O'Hagan A, Stevens JW, Campbell MJ (2005). Assurance in",
              "clinical trial design.", em("Pharmaceutical Statistics"),
              "4(3):187-201."),
      tags$li("Wang F, Gelfand AE (2002). A simulation-based approach to",
              "Bayesian sample size determination for performance under a",
              "given model and for separating models.",
              em("Statistical Science"), "17(2):193-208."),
      tags$li("Pan J, Banerjee S (2023). bayesassurance: An R package for",
              "calculating sample size and Bayesian assurance.",
              em("The R Journal"),
              tags$a(href = "https://journal.r-project.org/articles/RJ-2023-066/",
                     target = "_blank", "RJ-2023-066")))
  ))
}
