# =============================================================================
# Static content for the "Methods & help" tab.
# =============================================================================

methods_ui <- function() {
  withMathJax(div(
    style = "max-width: 920px;",

    h3("What this app does"),
    p("It helps you choose a sample size for a two-arm randomised trial",
      "(treatment vs control) by comparing two ways of answering \"how likely",
      "is this study to succeed?\":"),
    tags$ul(
      tags$li(strong("Frequentist power"), "assumes the true effect is known",
              "exactly (your best guess) and asks how often the usual test",
              "would be significant."),
      tags$li(strong("Bayesian assurance"), "(also called the probability of",
              "success) admits that the true effect is uncertain. It averages",
              "the chance of success over every effect size you consider",
              "plausible, weighted by how plausible you think it is.")),
    p("Assurance is usually lower than power when you are optimistic about the",
      "effect, because it also counts the scenarios in which the treatment",
      "works less well than hoped, or not at all."),

    h3("Outcome types"),
    tags$table(class = "table table-sm",
      tags$thead(tags$tr(tags$th("Outcome"), tags$th("Effect (working scale)"),
                         tags$th("Extra inputs"), tags$th("Simulation engine"))),
      tags$tbody(
        tags$tr(tags$td("Continuous"), tags$td("difference in means"),
                tags$td("outcome SD"), tags$td(code("bayesassurance::bayes_sim_unbalanced"))),
        tags$tr(tags$td("Continuous, baseline-adjusted (ANCOVA)"),
                tags$td("adjusted difference in means"),
                tags$td("outcome SD, baseline-outcome correlation \\(\\rho\\)"),
                tags$td(code("bayes_sim_unbalanced"), "with a simulated baseline covariate")),
        tags$tr(tags$td("Binary"), tags$td("log odds ratio, log risk ratio, or risk difference"),
                tags$td("control-group event rate"), tags$td("built-in binomial simulation")),
        tags$tr(tags$td("Time to event"), tags$td("log hazard ratio"),
                tags$td("control median, recruitment, follow-up, loss to follow-up"),
                tags$td("built-in patient-level survival simulation")))),

    h3("Quick guide to the inputs"),
    tags$dl(
      tags$dt("Design prior"),
      tags$dd("Your honest belief about the true effect before the study. For",
              "continuous outcomes and risk differences, enter a mean (best",
              "guess) and SD (about 95% of plausible effects lie within mean",
              "\u00B1 2 SD). For odds, risk and hazard ratios, enter the range",
              "you are 95% sure contains the true ratio; the app treats the",
              "ratio as log-normal with its best guess at the geometric",
              "midpoint. The design prior is only used to plan the study."),
      tags$dt("Analysis prior"),
      tags$dd("The prior that will actually be used when the trial data are",
              "analysed. Regulators and reviewers often prefer a sceptical",
              "prior (centred on no effect) or a vague one (very wide, which",
              "lets the data speak). Using the design prior here is simpler, but",
              "it builds your optimism into the final analysis."),
      tags$dt("Success threshold"),
      tags$dd("For one-sided tests. The no-effect value (0, or 1 for ratios)",
              "gives ordinary superiority. A value beyond it in the tested",
              "direction demands a clinically meaningful effect. A value on the",
              "other side gives a non-inferiority design, e.g. 'treatment <",
              "control' with a hazard-ratio threshold of 1.3."),
      tags$dt("Allocation ratio and dropout"),
      tags$dd("The ratio sets the treatment-group size relative to the",
              "control group. Dropout (continuous and binary outcomes) does not",
              "change the calculations, which refer to analysable participants;",
              "it only inflates the number to enrol. For time-to-event outcomes",
              "loss to follow-up is modelled directly: those participants are",
              "censored and contribute fewer events."),
      tags$dt("Target"),
      tags$dd("The probability of success you are aiming for (commonly 80% or",
              "90%). The app finds the smallest sample size that reaches it.")),

    h3("The common Bayesian framework"),
    p("Every outcome type is reduced to an effect \\(\\theta\\) on a working",
      "scale on which its estimate \\(\\hat\\theta\\) is approximately normal:",
      "\\(\\hat\\theta \\sim N(\\theta, v)\\), where the variance \\(v\\) depends",
      "on the sample sizes and, for binary and survival outcomes, on",
      "\\(\\theta\\) itself."),
    p("Design prior \\(\\theta \\sim N(m_d, s_d^2)\\); analysis prior",
      "\\(\\theta \\sim N(m_a, s_a^2)\\). The posterior after the trial is",
      "normal with precision \\(1/s_a^2 + 1/v\\). With threshold \\(C\\) and",
      "level \\(\\alpha\\), the trial is a success when"),
    tags$ul(
      tags$li("one-sided, '>': \\(P(\\theta > C \\mid \\text{data}) > 1-\\alpha\\)"),
      tags$li("one-sided, '<': \\(P(\\theta < C \\mid \\text{data}) > 1-\\alpha\\)"),
      tags$li("two-sided: \\(P(\\theta > 0 \\mid \\text{data}) > 1-\\alpha/2\\)",
              "or \\(P(\\theta < 0 \\mid \\text{data}) > 1-\\alpha/2\\). This",
              "counts a convincing effect in either direction, including the",
              "unexpected one; the summary says how much of the assurance comes",
              "from that.")),
    p("Assurance is",
      "$$\\text{Assurance}(n) = \\int P(\\text{success} \\mid \\theta, n)\\,",
      "\\pi_d(\\theta)\\, d\\theta,$$",
      "the probability of success averaged over the design prior",
      "\\(\\pi_d\\). The \"Success vs true effect\" tab shows",
      "\\(P(\\text{success} \\mid \\theta, n)\\) together with \\(\\pi_d\\)."),

    h3("Outcome-specific details"),
    h5("Continuous outcome"),
    p("\\(v = \\sigma^2 (1/n_T + 1/n_C)\\) with the outcome SD \\(\\sigma\\)",
      "known. Everything is exactly normal, so assurance has a closed form:",
      "marginally \\(\\hat\\theta \\sim N(m_d, s_d^2 + v)\\)."),
    h5("Continuous outcome adjusted for baseline (ANCOVA)"),
    p("Adjusting for a baseline value correlated \\(\\rho\\) with the outcome",
      "reduces the residual variance to \\(\\sigma^2(1-\\rho^2)\\). Because the",
      "slope is estimated and the arms' baseline means differ by chance,",
      "\\(v = \\sigma^2(1-\\rho^2)(1/n_T + 1/n_C)\\,(1 + 1/(N-4))\\), where",
      "\\(N = n_T + n_C\\) (Borm et al., 2007). The simulation generates",
      "baseline values and fits the full regression model with",
      code("bayes_sim_unbalanced"), "(design matrix: two group columns plus the",
      "baseline; flat analysis prior on the slope). Frequentist power uses the",
      "ANCOVA t-test with \\(N-3\\) degrees of freedom."),
    h5("Binary outcome"),
    p("Given the control-group event rate \\(p_C\\), the effect determines",
      "the treatment-group rate \\(p_T\\). Delta-method variances:",
      "log odds ratio \\(1/(n_T p_T q_T) + 1/(n_C p_C q_C)\\); log risk ratio",
      "\\(q_T/(n_T p_T) + q_C/(n_C p_C)\\); risk difference",
      "\\(p_T q_T/n_T + p_C q_C/n_C\\) (\\(q = 1-p\\)). As \\(v\\) depends on",
      "\\(\\theta\\), exact assurance is computed by numerical integration over",
      "the design prior (a fine grid over \\(\\pm 8\\) SD). The simulation",
      "draws a true effect from the design prior for every virtual trial,",
      "simulates binomial counts, and analyses them on the working scale",
      "(with a 0.5 continuity correction when a cell is empty). For risk",
      "ratios and differences, prior values implying event rates outside",
      "0-100% are truncated, and the app warns when that matters."),
    h5("Time to event"),
    p("Exponential survival with control median \\(M\\), so the control",
      "hazard is \\(\\lambda_C = \\log 2 / M\\) and \\(\\lambda_T = \\text{HR}",
      "\\times \\lambda_C\\). Participants join uniformly over the recruitment",
      "period \\(A\\), the analysis happens at \\(A + F\\), and loss to",
      "follow-up is a competing exponential hazard \\(\\eta\\) calibrated to",
      "the stated percentage over the average follow-up \\(F + A/2\\). The",
      "probability that a participant has an observed event is",
      "$$P_e = \\frac{\\lambda}{\\lambda+\\eta}\\left(1 - \\frac{e^{-(\\lambda+\\eta)F} -",
      "e^{-(\\lambda+\\eta)(A+F)}}{(\\lambda+\\eta)A}\\right),$$",
      "and the log hazard ratio has variance \\(v \\approx 1/D_T + 1/D_C\\),",
      "with expected events \\(D = n P_e\\) per arm. This is close to",
      "Schoenfeld's \\(4/D\\) for equal allocation and a hazard ratio near 1.",
      "What drives precision is the number of events, so the app reports",
      "expected events alongside sample sizes. The simulation generates",
      "entry times, event times and dropout times for every participant,",
      "applies administrative censoring, and estimates the log hazard ratio",
      "from the ratio of event rates (events / person-time) in the two arms."),

    h3("How it is computed"),
    tags$ul(
      tags$li(strong("Simulated assurance"), "(the default). Continuous and",
              "ANCOVA outcomes use", code("bayesassurance::bayes_sim_unbalanced()"),
              "(Pan & Banerjee). In its parameterisation prior variances are",
              "relative to the outcome variance, so a prior SD \\(s\\) enters as",
              "\\(s^2/\\sigma^2\\); the full mapping is documented in",
              code("R/calculations.R"), ". Binary and time-to-event outcomes use",
              "the app's own simulators described above. In every case each",
              "virtual trial draws its own true effect from the design prior,",
              "simulates data, analyses them with the analysis prior and checks",
              "the success rule. The shaded band is the 95% Monte Carlo interval."),
      tags$li(strong("Exact assurance"), "uses the closed form (continuous",
              "outcomes) or numerical integration (binary and survival), with",
              "the variance evaluated at each true effect. It drives the dotted",
              "check line, the sample-size finder, the sensitivity plots and the",
              "success-vs-effect curve. It agrees with the simulation to within",
              "Monte Carlo error except when very few events are expected, where",
              "the simulation (which analyses the actual counts) is the more",
              "accurate of the two."),
      tags$li(strong("Frequentist power"), "uses the design prior's centre as",
              "the true effect: the two-sample t-test (identical to",
              code("stats::power.t.test()"), "for equal groups) or the ANCOVA",
              "t-test for continuous outcomes, and a Wald z-test on the working",
              "scale for binary and survival outcomes, with the standard error",
              "evaluated at the assumed effect."),
      tags$li(strong("Assurance ceiling."), "As the sample size grows, the",
              "data overwhelm the analysis prior and the trial succeeds",
              "exactly when the true effect lies beyond the success threshold.",
              "Assurance therefore cannot exceed the design-prior probability",
              "of that event. If your target is above this ceiling, no sample",
              "size can reach it.")),

    h3("About the bayesassurance package"),
    p("The app uses the package's general linear-model simulator",
      code("bayes_sim_unbalanced()"), "for continuous outcomes. Several other",
      "functions were reviewed and deliberately not used:"),
    tags$ul(
      tags$li(code("assurance_nd_na()"), "(closed form) ties the analysis prior",
              "mean to the null value and does not match the exact",
              "posterior-probability assurance when the analysis prior is",
              "informative."),
      tags$li(code("bayes_sim_betabin()"), "(binary outcomes) draws the true",
              "proportions only once per call rather than once per simulated",
              "trial, so it does not average over the design prior. It also uses",
              "the same beta prior for design and analysis."),
      tags$li(code("bayes_sim_unknownvar()"), "(unknown variance) builds a",
              "default covariance matrix whose size does not match its own",
              "two-group design matrix and is very slow. Uncertainty about the",
              "outcome SD is instead explored on the Sensitivity tab."),
      tags$li("The package has no functions for time-to-event outcomes.")),

    h3("Limitations"),
    tags$ul(
      tags$li("Normal approximations on the working scale underlie the exact",
              "engine and the frequentist power for binary and survival",
              "outcomes; they are rough with very few events."),
      tags$li("The survival model assumes exponential event times and",
              "proportional hazards, and non-informative censoring. Non-constant",
              "hazards or delayed treatment effects need dedicated software."),
      tags$li("Nuisance quantities (outcome SD, correlation, control event",
              "rate, control median) are treated as known; the Sensitivity tab",
              "shows how much the answer depends on them."),
      tags$li("Clustered, longitudinal, count and multi-arm designs are not",
              "covered.")),

    h3("Tips"),
    tags$ul(
      tags$li("Simulation cost grows with the square of the sample size for",
              "continuous outcomes. Use the exact engine for quick exploration,",
              "then confirm with the simulation."),
      tags$li("Use the bookmark button to get a link that restores all your",
              "inputs."),
      tags$li("Save scenarios on the Results tab to compare assumptions, or",
              "outcome types, side by side.")),

    h3("References"),
    tags$ul(
      tags$li("O'Hagan A, Stevens JW (2001). Bayesian assessment of sample",
              "size for clinical trials of cost-effectiveness.",
              em("Medical Decision Making"), "21(3):219-230."),
      tags$li("O'Hagan A, Stevens JW, Campbell MJ (2005). Assurance in",
              "clinical trial design.", em("Pharmaceutical Statistics"),
              "4(3):187-201."),
      tags$li("Ren S, Oakley JE (2014). Assurance calculations for planning",
              "clinical trials with time-to-event outcomes.",
              em("Statistics in Medicine"), "33(1):31-45."),
      tags$li("Schoenfeld DA (1983). Sample-size formula for the",
              "proportional-hazards regression model.", em("Biometrics"),
              "39(2):499-503."),
      tags$li("Borm GF, Fransen J, Lemmens WA (2007). A simple sample size",
              "formula for analysis of covariance in randomized clinical",
              "trials.", em("Journal of Clinical Epidemiology"), "60(12):1234-1238."),
      tags$li("Wang F, Gelfand AE (2002). A simulation-based approach to",
              "Bayesian sample size determination for performance under a",
              "given model and for separating models.",
              em("Statistical Science"), "17(2):193-208."),
      tags$li("Pan J, Banerjee S (2023). bayesassurance: An R package for",
              "calculating sample size and Bayesian assurance.",
              em("The R Journal"),
              tags$a(href = "https://journal.r-project.org/articles/RJ-2023-066/",
                     target = "_blank", "RJ-2023-066")))
  ))
}
